from tkinter import *
from pymysql import *
from tkinter import messagebox as tm
from util import *
class EmployeeMaster(Frame):
	def __init__(self,master):
		super().__init__(master)
		
		self.lblId=Label(self,text='Employee Id')
		self.lblName=Label(self,text='Employee Name')
		self.lblDesig=Label(self,text='Designation')
		self.lblSalary=Label(self,text='Salary')
		self.lblAddress=Label(self,text='Address')
		self.lblPin=Label(self,text='Pin')
		self.lblCity=Label(self,text='City')
		self.lbLoginid=Label(self,text='User Name')
		self.lblPassword=Label(self,text='Password')
		self.lblType=Label(self,text='User Type')
		self.txtId=Entry(self)
		self.txtName=Entry(self)
		self.txtDesig=Entry(self)
		self.txtSalary=Entry(self)
		self.txtAddress=Entry(self)
		self.txtPin=Entry(self)
		self.txtCity=Entry(self)
		self.txtLoginid=Entry(self)
		self.txtPassword=Entry(self,show='*')
		self.txtType=Entry(self)
		self.btnSave=Button(self,text='Save',command=self.saveEmployee)
		
		self.lblId.grid(row=0,column=0)
		self.txtId.grid(row=0,column=1)
		self.lblName.grid(row=0,column=2)
		self.txtName.grid(row=0,column=3)
		self.lblDesig.grid(row=1,column=0)
		self.txtDesig.grid(row=1,column=1)
		self.lblSalary.grid(row=1,column=2)
		self.txtSalary.grid(row=1,column=3)
		self.lblAddress.grid(row=2,column=0)
		self.txtAddress.grid(row=2,column=1)
		self.lblPin.grid(row=2,column=2)
		self.txtPin.grid(row=2,column=3)
		self.lblCity.grid(row=3,column=0)
		self.txtCity.grid(row=3,column=1)
		self.lblType.grid(row=3,column=2)
		self.txtType.grid(row=3,column=3)
		self.lbLoginid.grid(row=4,column=0)
		self.txtLoginid.grid(row=4,column=1)
		self.lblPassword.grid(row=4,column=2)
		self.txtPassword.grid(row=4,column=3)
		self.btnSave.grid(columnspan=4)
		self.pack()
	def saveEmployee(self):
		ob=Connect()
		con=ob.conn()
		cur=con.cursor()
		id=(int)(self.txtId.get())
		name=self.txtName.get()
		desig=self.txtDesig.get()
		salary=(float)(self.txtSalary.get())
		pin=self.txtPin.get()
		city=self.txtCity.get()
		uid=self.txtLoginid.get()
		pwd=self.txtPassword.get()
		type=self.txtType.get()
		addr=self.txtAddress.get()
		i=cur.execute("insert into users values('%s','%s','%s')"%(uid,pwd,type))
		if i==1:
			j=cur.execute("insert into master values(%d,'%s','%s',%f,'%s','%s','%s','%s')"%(id,name,desig,salary,addr,pin,city,uid))
			if j==1:
				con.commit()
				self.txtId.delete(0,'end')
				self.txtName.delete(0,'end')
				self.txtDesig.delete(0,'end')
				self.txtSalary.delete(0,'end')
				self.txtPin.delete(0,'end')
				self.txtCity.delete(0,'end')
				self.txtLoginid.delete(0,'end')
				self.txtPassword.delete(0,'end')
				self.txtType.delete(0,'end')
				self.txtAddress.delete(0,'end')
		tm.showinfo('Emp Info','Record Saved')